FROM mongo:latest

COPY database/* /docker-entrypoint-initdb.d/

# RUN chmod +x /docker-entrypoint-initdb.d/importData.sh
# Use the default entrypoint script provided by the MongoDB image, which runs initialization scripts in the background
# ENTRYPOINT ["docker-entrypoint.sh"]
# CMD ["mongod"]