apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
        version: latest
    spec:
      containers:
      - name: express
        image: loppiko/cloud-project:express
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          value: mongodb://mongo-service:27017/mydatabase

---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001